# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlscan-cli" do
  desc ""
  homepage ""
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlscan"

  on_macos do
    on_intel do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v0.0.2/urlscan-cli_Darwin_x86_64.tar.gz"
      sha256 "649375dd64a2632879ddad60529d3fd9f587b932549fb4f55d2227b4fd6413be"
    end
    on_arm do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v0.0.2/urlscan-cli_Darwin_arm64.tar.gz"
      sha256 "76ed7e71bb712ef6f621d11fcf701914b72bcdb4e576a1feb53f2f57d03583ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v0.0.2/urlscan-cli_Linux_x86_64.tar.gz"
      sha256 "9e0480bc70ae49686a743176414d3f057647fdd7cf2318f9f76decb08f800446"
    end
    on_arm do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v0.0.2/urlscan-cli_Linux_arm64.tar.gz"
      sha256 "0a1f2a4f387e324d5d6785092a14a6e853afd438d497981ed4a74ce8fe5074a6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlscan"]
    end
  end

  # No zap stanza required
end
