# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlscan-cli" do
  name "urlscan-cli"
  desc ""
  homepage ""
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlscan"

  on_macos do
    on_intel do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_x86_64.tar.gz"
      sha256 "6d4159a558e992e4c8fd021ac26a68115bbff515761b0fd4032c319aeec357ee"
    end
    on_arm do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_arm64.tar.gz"
      sha256 "b7c5c83c06389e6cd663ac289d328a02719126c814532fc6d2a59962c7081236"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_x86_64.tar.gz"
      sha256 "587bf5723269fff4600eb1eb9886560c57c8495782208a38ef7338ff75f5af8f"
    end
    on_arm do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_arm64.tar.gz"
      sha256 "c67b3a23022ec550d42fe2822cca2674ea7cd49d614a2309b4d0cc8f8d03aa7c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlscan"]
    end
  end

  # No zap stanza required
end
