# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlscan-cli" do
  name "urlscan-cli"
  desc ""
  homepage ""
  version "2026.06.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlscan"

  on_macos do
    on_intel do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_x86_64.tar.gz"
      sha256 "aebd0a3346dc478254a9f4437e73df70be39e49301414f5575b35ac72353b8da"
    end
    on_arm do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_arm64.tar.gz"
      sha256 "9db95805f60860642ddf4cb3a0929fa257bcf398f5de37bd039db9cb837c6d31"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_x86_64.tar.gz"
      sha256 "9812a9dc8629524b61277be5f7f8bb45fa4c0bbbd9da6780887ae64daf42919f"
    end
    on_arm do
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_arm64.tar.gz"
      sha256 "3d2f3d9aaaf7c1a4c84b421cbc8e41ff63615e9d11c4a57c02fe604de87c9b58"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlscan"]
    end
  end

  # No zap stanza required
end
